.editorconfig, .npmignore
Adds missing config files that broke the npm package build.
=> Jbaker/repo setup fixes - add missing files

.gitignore, .stylelintrc, README.md, docTemplates/README.md, docs/partials/cdnDeps.md, docs/partials/installDeps.md, package-lock.json, scripts/generateDocs.js, src/auro-datepicker.js, src/style.scss
**Fixes:** #35, #38
Fix error state help text so that it clears after selecting a date. 
Add peer dependency information to docs.
Update to latest version of auro-dropdown to use improved template layout so that the input in the trigger is full width.
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and …
=> Dynamic width, peer deps in docs, error state fix

src/auro-datepicker.js
**Fixes:** #44
Update string formatting for dates received from auro-calendar before inserting to auro-input.
**Thank you for your submission!**
=> fix(format): consistent date format fix #44

docs/figma.md, package-lock.json
**Fixes:** #49 
The design support tab for `auro-datepicker` displayed an incorrect figma link.
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the …
=> Incorrect figma link on doc site

package-lock.json, package.json, src/auro-datepicker.js, src/style.scss
**Fixes:** #31, #47
Uses the new `activeLabel` attribute from auro-input. Removes styles that are no longer needed after the auro-input update. This does not create any feature / API change for the user. …
=> fix(input): use new activeLabel attribute #31 #47

README.md, apiExamples/focus.js, apiExamples/value.html, apiExamples/value.js, demo/api.html, demo/apiExamples.md, demo/examples.js, demo/index.html, docs/api.md, docs/partials/apiExamples.md, package-lock.json, package.json, src/auro-datepicker.js, src/style.scss, test/auro-datepicker.test.js
**Fixes:** #51, #54
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your …
=> Update to use of value attribute and examples

apiExamples/error.html, apiExamples/value.js, demo/apiExamples.md, demo/demo.md, docs/api.md, docs/partials/apiExamples.md, package-lock.json, package.json, src/auro-datepicker.js, src/style.scss, test/auro-datepicker.test.js, web-test-runner.config.mjs
**Fixes:** #58, #56, #42, #60
Significant changes to the workflow for setting the value. This corrects issues where the logic was previously recursive and causing the wrong values to end up in the input. This also corrects the behavior where a required datepicker was completely broken and no value could be set. 
This also adds correct validation when setting the value of the datepicker.
_Pull Requests will be evaluated by their quality of update and …
=> fix(value): improve value setting workflow #58

demo/apiExamples.md, package-lock.json, package.json
Use latest release of auro-dropdown.
=> fix(dropdown): use latest version of dropdown

package-lock.json, package.json
**Fixes:** #68 
Update dependencies to use the latest version of auro-input.
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the …
=> Update package to fix auro-input bug

package-lock.json, package.json
**Fixes:** #70 
Update the versioning on the auro-input dependency to implement the latest hover state changes from auro-input.
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a …
=> Update auro-input dependency version

src/style.scss
**Fixes:** #62
Fixed height of the bib
=> fix(style): fixed height of the bib #62

apiExamples/alertValue.js, demo/api.md, docs/partials/api.md, package-lock.json, src/auro-datepicker.js
**Fixes:** #74 
Gave the `valueSet` example a more detailed description that explains to the user what to look for when the `auroDatePicker-valueSet` event is triggered in the example.
- [] Revision of an existing capability
_Pull Requests will be evaluated by their quality of update and whether …
=> Give the valueSet example a more detailed description

src/style.scss
**Fixes:** #88 
Increase the `min-height` of the calendar wrapper to `518px` to stop the calendar height from increasing in the UI for months that have 6 rows of dates.
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this …
=> Increase calendar height

src/auro-datepicker.js, test/auro-datepicker.test.js
**Fixes:** #97 
Pass the `required` attribute to the `auro-input` element in the shadow DOM
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter …
=> Pass `required` attribute down to auro-input element

.github/workflows/testPublish.yml, src/auro-datepicker.js, test/auro-datepicker.test.js
**Fixes:** #97 
* Pass the `required` attribute to the `auro-input` element in the shadow DOM
* Update semantic release versioning
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered …
=> Apply required attribute to input

demo/index.md, src/auro-calendar.js, src/auro-datepicker.js, src/style-auro-calendar-cell.scss, src/style-auro-calendar-month.scss, src/style-auro-calendar.scss, src/style.scss, test/auro-datepicker.test.js
**Fixes:** # (issue, if applicable) …
=> Fix bugs based off of date range support branch

apiExamples/alertValue.js, apiExamples/error.js, apiExamples/focus.js, apiExamples/monthNames.js, apiExamples/updateMaxDate.js, apiExamples/updateMinDate.js, apiExamples/validity.js, demo/api.html, demo/api.js, demo/api.md, demo/api.min.js, demo/index.html, demo/index.js, demo/index.min.js, package-lock.json, package.json, rollup.config.js, scripts/prepExampleFiles.js
**Fixes:** #121
update bundler and add new script to make a JS file usable by AuroDocSite so that all the JS examples work
-- Auro …
=> perf(examples): update example js code so it works on the docsite #121

README.md
**Fixes:** #126
Fix the URL for the CDN bundle
=> docs(readme): correct the URL for the CDN bundle #126

README.md, docs/partials/installDeps.md
**Fixes:** #129
Update documented list of peer dependencies
=> docs(deps): update list of peer dependencies #129

README.md, demo/api.md, demo/demo.md, docTemplates/README.md, package-lock.json, package.json, scripts/generateDocs.js, src/style-auro-calendar-cell.scss, tsconfig.json
**Fixes:** #118, #125
* Add support for typscript users
* Change selected calendar-cell `hover` background color
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation …
=> Add typescript support and change color of calendar cell

.npmignore, package.json
**Fixes:** #146 
Changes to be committed:
modified:   .npmignore
modified:   package.json
This PR updates the building process of the element and produces the following packaged deliverable. it should be noted that the same 56 files are in the package, but simply the location was changed. There is no performance increase or package size change with this update. 
```
/datepicker/package
├── CHANGELOG.md
├── LICENSE
├── README.md
├── demo
|  ├── api.js
|  ├── …
```
=> Update npm package configs

package-lock.json, src/auro-calendar-cell.js
**Fixes:** # (issue, if applicable)
Fix classmap style application to properly handle in range styles
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the …
=> Fix range support styles

src/auro-datepicker.js
**Fixes:** #188
Change the code to always fire the valueSet event when the value or valueEnd properties are changed.
-- Auro Design …
=> fix(event): always fire notify event when value changes #188

.github/ISSUE_TEMPLATE/bug_report.yml, README.md, demo/api.html, demo/index.html
**Resolves:** # (issue, if applicable) …
=> perf: alaskaairux ref updates

package-lock.json, package.json, scripts/version.mjs, src/auro-datepicker.js, src/dropdownVersion.js, src/inputVersion.js, src/style.scss, test/auro-datepicker.test.js
**Resolves:** #163, #166
Implement dependency versioning standard for `auro-input` and `auro-dropdown`, similar to how we do it in `auro-combobox`
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is …
=> Implement dependency versioning standard

apiExamples/dynamicSlot.html, apiExamples/dynamicSlot.js, demo/api.md, demo/api.min.js, docs/partials/api.md, src/auro-calendar-cell.js, src/auro-calendar.js
**Resolves:** #198
* Update insertion of slot content to happen when datepicker is opened (this change mainly affects dynamic content)
* Update dynamic slot content example to reflect use case for flight search
_Pull Requests will be evaluated by their quality of update and whether it is …
=> Update handling of slot content

test/auro-datepicker.test.js
Fix a broken test that was causing the semantic releaser to fail due to a test timeout
=> perf(tests): fix broken tests causing them to time out

test/auro-datepicker.test.js
This change updates the date comparison in the tests to work in any time zone. This resolves the issue of tests failing in the cloud found here: https://github.com/AlaskaAirlines/auro-datepicker/actions/runs/8808360146/job/24207884952
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers …
=> perf(tests): update time comparison to tests to work in any time zone.

src/style-auro-calendar.scss
**Resolves:** #222
Set calendar height to 100dvh which will account for the mobile address bar dynamically being shown.
-- Auro Design …
=> Update height calculation for mobile address bar

src/auro-calendar.js
**Resolves:** #244 
This commit updates the endpoint for the requested Auro icons to use the updated ES6/SSR support versus the legacy format.
On branch dsande/hotfix/icons/244
Changes to be committed:
modified:   src/auro-calendar.js
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers …
=> Update icon endpoint

.github/settings.yml
**Resolves:** # (issue, if applicable) …
=> Trigger major release

CHANGELOG.md
**Resolves:** # (issue, if applicable) …
=> Remove 3.0.0 beta release from changelog

demo/api.min.js, demo/index.min.js, vendor/wc-range-datepicker/range-date-picker-cell.js
=> fix: add correct registration process for cell

demo/api.min.js, demo/index.min.js, package-lock.json, vendor/wc-range-datepicker/range-date-picker-cell.js, vendor/wc-range-datepicker/range-datepicker-calendar.js
=> fix: refactor all vendor component registration

demo/api.min.js, demo/index.min.js, vendor/wc-range-datepicker/range-datepicker-calendar.js
=> perf: add extensions for mwc imports
